# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creador', '0003_auto_20170326_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('repositorio', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='tareas2',
        ),
    ]
